# Site settings
class:
  short: Advanced GIS
  long: Advanced GIS
  term: Spring 2021
school:
  name: GPIA at The New School
  link: http://www.newschool.edu/public-engagement/ma-ms-international-affairs/
email:
description: > # this means to ignore newlines until "baseurl:"
  Advanced GIS projects for Fall 2021
baseurl: /adv-spring2021/
url: http://gpia-gis.github.io
twitter_username: TheNewSchool
github_username:  gpia-gis

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    author: name
    output: true
    permalink: /projects/:path/
